name=str(input("Enter your name:"))
num=int(input("Enter your rollno:"))
marks=float(input("Enter Your marks:"))
List=list(input("Enter the list:"))
Tuple=tuple(input("Enter the tuple:"))
Set=set(input("Enter the set value:"))
print("Your name is :",name)
print("Your roll_no: :",num)
print("Your marks is :",marks)
print("Your list is:",List)
print("Your Tuple is :",Tuple)
print("Your Set is :",Set)
